name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.APPUSER_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 as appuser
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null appuser@18.184.47.50 <<EOF
          YARN_PATH=$(whereis yarn | awk '{print $2}')
          PM2_PATH=$(whereis pm2 | awk '{print $2}')
          echo "export PATH=$PATH:$YARN_PATH:$PM2_PATH" >> $GITHUB_ENV
          cd apps/doogle-meet/
          git pull
          /home/appuser/.nvm/versions/node/v20.12.0/bin/yarn
          /home/appuser/.nvm/versions/node/v20.12.0/bin/yarn build
          /home/appuser/.nvm/versions/node/v20.12.0/bin/pm2 delete doogle-meet
          /home/appuser/.nvm/versions/node/v20.12.0/bin/yarn start yarn --name doogle-meet -- start
          /home/appuser/.nvm/versions/node/v20.12.0/bin/yarn log --nostream
          EOF
