name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.APPUSER_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 as appuser
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null appuser@18.184.47.50 <<EOF
          cd apps/doogle-meet/
          git pull
          yarn install
          yarn build
          pm2 delete doogle-meet
          pm2 start yarn --name doogle-meet -- start
          pm2 log --nostream
          EOF
