name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.APPUSER_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 as appuser
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t  appuser@18.184.47.50 <<EOF
          YARN_PATH=$(whereis yarn | awk '{print $2}')
          PM2_PATH=$(whereis pm2 | awk '{print $2}')
          NODE_PATH=$(whereis node | awk '{print $2}')
          PATH=$PATH:$YARN_PATH:$PM2_PATH
          pwd 
          echo "printing path..." 
          source ~/.bashrc 
          echo $PATH
          EOF
